name: Continuous Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Google Cloud Auth
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy to Google Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: ${{ secrets.GCP_APP_NAME }}
        region: europe-west1
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}